# Generated by Django 6.0.3 on 2026-04-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_menuitems_id_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateField(),
        ),
    ]
